Symmetries = [
  [0, 1, 2, 3],
  [1, 2, 3, 0],
  [2, 3, 0, 1],
  [3, 0, 1, 2]
]

# real irrep, momentum 0
[k_0]
characters=[1.0, 1.0, 1.0, 1.0]

# complex irrep, momentum pi/2
[k_pi2]
characters=[
  [1.0, 0.0], 
  [0.0, 1.0], 
  [-1.0, 0.0],
  [0.0, -1.0]
]

# real irrep, momentum pi
[k_pi]
characters=[1.0, -1.0, 1.0, -1.0]

# real irrep on subgroup
[k_pi2_half]
characters=[1.0, -1.0]
allowed_symmetries=[0, 2]