# Interaction Shastry Sutherland with L=5 and W=4
Interactions = [["J", "SdotS", 0, 4], 
["J", "SdotS", 0, 16], 
["J", "SdotS", 0, 1], 
["J", "SdotS", 0, 3], 
["J", "SdotS", 1, 5], 
["J", "SdotS", 1, 17], 
["J", "SdotS", 1, 2], 
["J", "SdotS", 2, 6], 
["J", "SdotS", 2, 18], 
["J", "SdotS", 2, 3], 
["J", "SdotS", 3, 7], 
["J", "SdotS", 3, 19], 
["J", "SdotS", 4, 8], 
["J", "SdotS", 4, 5], 
["J", "SdotS", 4, 7], 
["J", "SdotS", 5, 9], 
["J", "SdotS", 5, 6], 
["J", "SdotS", 6, 10],
["J", "SdotS", 6, 7], 
["J", "SdotS", 7, 11], 
["J", "SdotS", 8, 12], 
["J", "SdotS", 8, 9], 
["J", "SdotS", 8, 11], 
["J", "SdotS", 9, 13], 
["J", "SdotS", 9, 10], 
["J", "SdotS", 10, 14],
["J", "SdotS", 10, 11], 
["J", "SdotS", 11, 15], 
["J", "SdotS", 12, 16], 
["J", "SdotS", 12, 13], 
["J", "SdotS", 12, 15], 
["J", "SdotS", 13, 17], 
["J", "SdotS", 13, 14], 
["J", "SdotS", 14, 18], 
["J", "SdotS", 14, 15], 
["J", "SdotS", 15, 19], 
["J", "SdotS", 16, 17], 
["J", "SdotS", 16, 19], 
["J", "SdotS", 17, 18], 
["J", "SdotS", 18, 19], 
["Jd", "SdotS", 0, 5], 
["Jd", "SdotS", 6, 9], 
["Jd", "SdotS", 2, 7], 
["Jd", "SdotS", 4, 11], 
["Jd", "SdotS", 8, 13], 
["Jd", "SdotS", 14, 17], 
["Jd", "SdotS", 10, 15], 
["Jd", "SdotS", 12, 19], 
["Jd", "SdotS", 1, 16], 
["Jd", "SdotS", 3, 18]]
N = [20]
